Organizations:
- &org1
  Name: org1MSP
  ID: org1MSP
  MSPDir: ./crypto/peerOrganizations/org1.scientificideas.org/msp
  Policies: &org1MSPPolicies
    Readers:
      Type: Signature
      Rule: "OR('org1MSP.member')"
    Writers:
      Type: Signature
      Rule: "OR('org1MSP.member')"
    Admins:
      Type: Signature
      Rule: "OR('org1MSP.admin')"
  AnchorPeers:
    - Host: peer0.org1.scientificideas.org
      Port: 7051
  OrdererEndpoints:
  - orderer0.org1.scientificideas.org:7050
  - orderer1.org1.scientificideas.org:7050
  - orderer2.org1.scientificideas.org:7050
  - orderer3.org1.scientificideas.org:7050
- &org2
  Name: org2MSP
  ID: org2MSP
  MSPDir: ./crypto/peerOrganizations/org2.scientificideas.org/msp
  Policies: &org2MSPPolicies
    Readers:
      Type: Signature
      Rule: "OR('org2MSP.member')"
    Writers:
      Type: Signature
      Rule: "OR('org2MSP.member')"
    Admins:
      Type: Signature
      Rule: "OR('org2MSP.admin')"
  AnchorPeers:
    - Host: peer0.org2.scientificideas.org
      Port: 7051
  OrdererEndpoints:
  - orderer0.org2.scientificideas.org:7050
- &org3
  Name: org3MSP
  ID: org3MSP
  MSPDir: ./crypto/peerOrganizations/org3.scientificideas.org/msp
  Policies: &org3MSPPolicies
    Readers:
      Type: Signature
      Rule: "OR('org3MSP.member')"
    Writers:
      Type: Signature
      Rule: "OR('org3MSP.member')"
    Admins:
      Type: Signature
      Rule: "OR('org3MSP.admin')"
  AnchorPeers:
    - Host: peer0.org3.scientificideas.org
      Port: 7051
  OrdererEndpoints:
  - orderer0.org3.scientificideas.org:7050
- &org4
  Name: org4MSP
  ID: org4MSP
  MSPDir: ./crypto/peerOrganizations/org4.scientificideas.org/msp
  Policies: &org4MSPPolicies
    Readers:
      Type: Signature
      Rule: "OR('org4MSP.member')"
    Writers:
      Type: Signature
      Rule: "OR('org4MSP.member')"
    Admins:
      Type: Signature
      Rule: "OR('org4MSP.admin')"
  AnchorPeers:
    - Host: peer0.org4.scientificideas.org
      Port: 7051
  OrdererEndpoints:
  - orderer0.org4.scientificideas.org:7050

Channel: &ChannelDefaults
  Capabilities:
    V2_0: true
  Policies: &DefaultPolicies
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

Profiles:
  Genesis:
    <<: *ChannelDefaults
    Orderer:
      OrdererType: smartbft
      Addresses:
      - orderer0.org1.scientificideas.org:7050
      - orderer1.org1.scientificideas.org:7050
      - orderer2.org1.scientificideas.org:7050
      - orderer3.org1.scientificideas.org:7050
      - orderer0.org2.scientificideas.org:7050
      - orderer0.org3.scientificideas.org:7050
      - orderer0.org4.scientificideas.org:7050
      BatchTimeout: 1s
      BatchSize:
        MaxMessageCount: 100
        AbsoluteMaxBytes: 98 MB
        PreferredMaxBytes: 512 KB
      Capabilities:
        V2_0: true
      SmartBFT:
        Options:
          LeaderRotation: 0
          DecisionsPerLeader: 0
          RequestBatchMaxCount: 100
          RequestBatchMaxBytes: 10485760
          RequestBatchMaxInterval: 500ms
          IncomingMessageBufferSize: 1000
          RequestPoolSize: 100
          RequestForwardTimeout: 2s
          RequestComplainTimeout: 20s
          RequestAutoRemoveTimeout: 3m
          ViewChangeResendInterval: 5s
          ViewChangeTimeout: 20s
          LeaderHeartbeatTimeout: 1m
          LeaderHeartbeatCount: 10
          CollectTimeout: 1s
          SyncOnStart: false
          SpeedUpViewChange: false
          RequestMaxBytes: 512000
          RequestPoolSubmitTimeout: 5s
        Consenters:
        - Host: orderer1.org1.scientificideas.org
          Port: 7050
          ClientTLSCert: ./crypto/peerOrganizations/org1.scientificideas.org/peers/orderer0.org1.scientificideas.org/tls/server.crt
          ServerTLSCert: ./crypto/peerOrganizations/org1.scientificideas.org/peers/orderer0.org1.scientificideas.org/tls/server.crt
          MSPID: org1MSP
          Identity: ./crypto/peerOrganizations/org1.scientificideas.org/peers/orderer0.org1.scientificideas.org/msp/signcerts/orderer0.org1.scientificideas.org-cert.pem
          ConsenterId: 1
        - Host: orderer1.org1.scientificideas.org
          Port: 7050
          ClientTLSCert: ./crypto/peerOrganizations/org1.scientificideas.org/peers/orderer1.org1.scientificideas.org/tls/server.crt
          ServerTLSCert: ./crypto/peerOrganizations/org1.scientificideas.org/peers/orderer1.org1.scientificideas.org/tls/server.crt
          MSPID: org1MSP
          Identity: ./crypto/peerOrganizations/org1.scientificideas.org/peers/orderer1.org1.scientificideas.org/msp/signcerts/orderer1.org1.scientificideas.org-cert.pem
          ConsenterId: 2
        - Host: orderer2.org1.scientificideas.org
          Port: 7050
          ClientTLSCert: ./crypto/peerOrganizations/org1.scientificideas.org/peers/orderer2.org1.scientificideas.org/tls/server.crt
          ServerTLSCert: ./crypto/peerOrganizations/org1.scientificideas.org/peers/orderer2.org1.scientificideas.org/tls/server.crt
          MSPID: org1MSP
          Identity: ./crypto/peerOrganizations/org1.scientificideas.org/peers/orderer2.org1.scientificideas.org/msp/signcerts/orderer2.org1.scientificideas.org-cert.pem
          ConsenterId: 3
        - Host: orderer3.org1.scientificideas.org
          Port: 7050
          ClientTLSCert: ./crypto/peerOrganizations/org1.scientificideas.org/peers/orderer3.org1.scientificideas.org/tls/server.crt
          ServerTLSCert: ./crypto/peerOrganizations/org1.scientificideas.org/peers/orderer3.org1.scientificideas.org/tls/server.crt
          MSPID: org1MSP
          Identity: ./crypto/peerOrganizations/org1.scientificideas.org/peers/orderer3.org1.scientificideas.org/msp/signcerts/orderer3.org1.scientificideas.org-cert.pem
          ConsenterId: 4
        - Host: orderer0.org2.scientificideas.org
          Port: 7050
          ClientTLSCert: ./crypto/peerOrganizations/org2.scientificideas.org/peers/orderer0.org2.scientificideas.org/tls/server.crt
          ServerTLSCert: ./crypto/peerOrganizations/org2.scientificideas.org/peers/orderer0.org2.scientificideas.org/tls/server.crt
          MSPID: org2MSP
          Identity: ./crypto/peerOrganizations/org2.scientificideas.org/peers/orderer0.org2.scientificideas.org/msp/signcerts/orderer0.org2.scientificideas.org-cert.pem
          ConsenterId: 5
        - Host: orderer0.org3.scientificideas.org
          Port: 7050
          ClientTLSCert: ./crypto/peerOrganizations/org3.scientificideas.org/peers/orderer0.org3.scientificideas.org/tls/server.crt
          ServerTLSCert: ./crypto/peerOrganizations/org3.scientificideas.org/peers/orderer0.org3.scientificideas.org/tls/server.crt
          MSPID: org3MSP
          Identity: ./crypto/peerOrganizations/org3.scientificideas.org/peers/orderer0.org3.scientificideas.org/msp/signcerts/orderer0.org3.scientificideas.org-cert.pem
          ConsenterId: 6
        - Host: orderer0.org4.scientificideas.org
          Port: 7050
          ClientTLSCert: ./crypto/peerOrganizations/org4.scientificideas.org/peers/orderer0.org4.scientificideas.org/tls/server.crt
          ServerTLSCert: ./crypto/peerOrganizations/org4.scientificideas.org/peers/orderer0.org4.scientificideas.org/tls/server.crt
          MSPID: org4MSP
          Identity: ./crypto/peerOrganizations/org4.scientificideas.org/peers/orderer0.org4.scientificideas.org/msp/signcerts/orderer0.org4.scientificideas.org-cert.pem
          ConsenterId: 7
      Organizations:
      - *org1
      - *org2
      - *org3
      - *org4
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: ANY Readers
        Writers:
          Type: ImplicitMeta
          Rule: ANY Writers
        Admins:
          Type: ImplicitMeta
          Rule: MAJORITY Admins
        BlockValidation:
          Type: ImplicitOrderer
          Rule: SMARTBFT
    Consortiums:
      SampleConsortium:
        Organizations:
        - *org1
        - *org2
        - *org3
        - *org4
  MyChannel:
    <<: *ChannelDefaults
    Consortium: SampleConsortium
    Application:
      Capabilities:
        V2_0: true
      Organizations:
      - *org1
      - *org2
      - *org3
      - *org4
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: ANY Readers
        Writers:
          Type: ImplicitMeta
          Rule: ANY Writers
        Admins:
          Type: ImplicitMeta
          Rule: MAJORITY Admins
        LifecycleEndorsement:
          Type: ImplicitMeta
          Rule: "MAJORITY Endorsement"
        Endorsement:
          Type: ImplicitMeta
          Rule: "MAJORITY Endorsement"

