OrdererOrgs:
  - Name: Org1
    Domain: org1.scientificideas.org
    EnableNodeOUs: false
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3
    Users:
      Count: 2

