PeerOrgs:
  - Name: Org1
    Domain: org1.scientificideas.org
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3
      - Hostname: orderer4
      - Hostname: orderer5
      - Hostname: orderer6
      - Hostname: orderer7
      - Hostname: orderer8
      - Hostname: orderer9
      - Hostname: orderer10
      - Hostname: peer0
      - Hostname: peer1
    Users:
      Count: 10

  - Name: Org2
    Domain: org2.scientificideas.org
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
      - Hostname: peer0
    Users:
      Count: 1

  - Name: Org3
    Domain: org3.scientificideas.org
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
      - Hostname: peer0
    Users:
      Count: 1

  - Name: Org4
    Domain: org4.scientificideas.org
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
      - Hostname: peer0
    Users:
      Count: 1
