PeerOrgs:
  - Name: Org1
    Domain: org1.scientificideas.org
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3
    Users:
      Count: 2

  - Name: Org2
    Domain: org2.scientificideas.org
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
    Users:
      Count: 1

  - Name: Org3
    Domain: org3.scientificideas.org
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
    Users:
      Count: 1

  - Name: Org4
    Domain: org4.scientificideas.org
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
    Users:
      Count: 1
