version: '2.1'

volumes:
  orderer0.org1.scientificideas.org:
  orderer1.org1.scientificideas.org:
  orderer2.org1.scientificideas.org:
  orderer3.org1.scientificideas.org:

networks:
  net:

services:
  orderer0.org1.scientificideas.org:
    extends:
      file: orderer-base.yaml
      service: orderer-base
    container_name: orderer0.org1.scientificideas.org
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LOCALMSPID=org1MSP
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ./genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto/peerOrganizations/org1.scientificideas.org/peers/orderer0.org1.scientificideas.org/msp:/var/hyperledger/orderer/msp
        - ./crypto/peerOrganizations/org1.scientificideas.org/peers/orderer0.org1.scientificideas.org/tls/:/var/hyperledger/orderer/tls
    networks:
      - net
    ports:
      - 7050:7050
      - 9040:8443

  orderer1.org1.scientificideas.org:
    extends:
      file: orderer-base.yaml
      service: orderer-base
    container_name: orderer1.org1.scientificideas.org
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LOCALMSPID=org1MSP
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ./genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto/peerOrganizations/org1.scientificideas.org/peers/orderer1.org1.scientificideas.org/msp:/var/hyperledger/orderer/msp
        - ./crypto/peerOrganizations/org1.scientificideas.org/peers/orderer1.org1.scientificideas.org/tls/:/var/hyperledger/orderer/tls
    networks:
      - net
    ports:
      - 7150:7050
      - 9041:8443

  orderer2.org1.scientificideas.org:
    extends:
      file: orderer-base.yaml
      service: orderer-base
    container_name: orderer2.org1.scientificideas.org
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LOCALMSPID=org1MSP
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ./genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto/peerOrganizations/org1.scientificideas.org/peers/orderer2.org1.scientificideas.org/msp:/var/hyperledger/orderer/msp
        - ./crypto/peerOrganizations/org1.scientificideas.org/peers/orderer2.org1.scientificideas.org/tls/:/var/hyperledger/orderer/tls
    networks:
      - net
    ports:
      - 7250:7050
      - 9042:8443

  orderer3.org1.scientificideas.org:
    extends:
      file: orderer-base.yaml
      service: orderer-base
    container_name: orderer3.org1.scientificideas.org
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LOCALMSPID=org1MSP
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ./genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto/peerOrganizations/org1.scientificideas.org/peers/orderer3.org1.scientificideas.org/msp:/var/hyperledger/orderer/msp
        - ./crypto/peerOrganizations/org1.scientificideas.org/peers/orderer3.org1.scientificideas.org/tls/:/var/hyperledger/orderer/tls
    networks:
      - net
    ports:
      - 7350:7050
      - 9043:8443

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=system
      - GOPATH=/opt/gopath
      #- CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=orderer.consensus.smartbft=debug:grpc=debug
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.scientificideas.org:7051
      - CORE_PEER_LOCALMSPID=org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.scientificideas.org/peers/peer0.org1.scientificideas.org/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.scientificideas.org/peers/peer0.org1.scientificideas.org/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.scientificideas.org/peers/peer0.org1.scientificideas.org/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.scientificideas.org/users/Admin@org1.scientificideas.org/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - ./crypto:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
        - ./:/opt/gopath/src/github.com/hyperledger/fabric/peer/config
    networks:
      - net
